autofocus:
  ros__parameters:
    autofocus_enabled: false
    control_rate: 10.0
    data_path: /data/autofocus
    ehc_distance: 0.05
    focus_algorithm: default
    focus_metric: sobel
    image_topic: /camera/image_raw/compressed
    object: ''
    roi_height: 100
    roi_width: 100
    roi_x: 0.5
    roi_y: 0.5
    save_data: false
    use_sim_time: false
gui:
  ros__parameters:
    data_path: /data/ViewpointGenerationData
    file_name: teapot
    show_axes: false
    show_curvatures: false
    show_fov_clusters: false
    show_grid: false
    show_mesh: true
    show_model_bounding_box: false
    show_noise_points: false
    show_path: false
    show_point_cloud: false
    show_region_view_manifolds: false
    show_regions: false
    show_reticle: true
    show_skybox: false
    show_viewpoints: false
    use_sim_time: false
task_planning:
  ros__parameters:
    controller_manager_name: /controller_manager
    data_path: /data/ViewpointGenerationData
    selected_region: 2
    selected_viewpoint: 0
    servo_controllers:
    - ur5e_forward_position_controller
    - turntable_forward_position_controller
    servo_node_name: servo_node
    trajectory_controllers:
    - inspection_cell_controller
    use_sim_time: false
    viewpoints_file: /data/ViewpointGenerationData/teapot_in/10000points_regions/3_regions_227_clusters_2025-10-22_00-15-18_optimized2025-10-22_00-15-20.json
viewpoint_generation:
  ros__parameters:
    model.camera.dof: 0.02
    model.camera.focal_distance: 0.3
    model.camera.fov.height: 0.05
    model.camera.fov.width: 0.05
    model.mesh.file: /data/ViewpointGenerationData/teapot.stl
    model.mesh.units: in
    model.point_cloud.curvature.file: /data/ViewpointGenerationData/teapot_in/10000points_12nn_curvatures.npy
    model.point_cloud.curvature.knn_neighbors: 12
    model.point_cloud.curvature.threshold: 0.1
    model.point_cloud.file: /data/ViewpointGenerationData/teapot_in/10000points.ply
    model.point_cloud.sampling.number_of_points: 10000
    model.point_cloud.units: m
    regions.file: /data/ViewpointGenerationData/teapot_in/10000points_regions/3_regions_227_clusters_2025-10-22_00-15-18_optimized2025-10-22_00-15-20.json
    regions.fov_clustering.beta_weight: 1.0
    regions.fov_clustering.k-means.maximum_iterations: 100
    regions.fov_clustering.k-means.normal_weight: 1.0
    regions.fov_clustering.k-means.number_of_runs: 9
    regions.fov_clustering.k-means.point_weight: 1.0
    regions.fov_clustering.lambda_weight: 1.0
    regions.fov_clustering.max_point_out_percentage: 0.001
    regions.region_growth.max_cluster_size: 100000
    regions.region_growth.min_cluster_size: 100
    regions.region_growth.normal_angle_threshold: 112.07499694824219
    regions.region_growth.seed_threshold: 0.1
    settings.cuda_enabled: false
    settings.data_path: /data/ViewpointGenerationData
    use_sim_time: false
    viewpoints.projection.nothing: ''
    viewpoints.traversal: ''
    visualize: false
viewpoint_traversal:
  ros__parameters:
    multiplanning: false
    planner: ompl
    planning_group: disc_to_ur5e
    use_2opt: true
    use_sim_time: false
    visualize: false
    workspace.max_x: 1.0
    workspace.max_y: 1.0
    workspace.max_z: 1.0
    workspace.min_x: -1.0
    workspace.min_y: -1.0
    workspace.min_z: -1.0
