admittance_control:
  ros__parameters:
    accel_topic: /admittance/accel_cmds
    autofocus_wrench_topic: /autofocus/wrench_cmds
    fluid_viscosity: 1.0
    frame_id: eoat_camera_link
    max_angular_speed: 0.0
    max_linear_speed: 0.0
    orientation_wrench_topic: /orientation_controller/wrench_cmds
    publish_rate: 10.0
    servo_twist_topic: /servo_node/delta_twist_cmds
    sphere_mass: 2.5
    sphere_radius: 0.65
    start_type_description_service: true
    teleop_wrench_topic: /teleop/wrench_cmds
autofocus:
  ros__parameters:
    control_rate: 50.0
    deriv_tau: 0.05
    distance_topic: /orientation_controller/focal_distance_m
    drive_button: 3
    fit_enabled: true
    fit_min_points: 5
    fit_peak_fraction: 0.5
    fluid_viscosity: 1.0
    focus_axis_sign: 1.0
    focus_metric: fswm
    focus_tolerance_m: 0.001
    frame_id: eoat_camera_link
    image_topic: /pi_camera/image_raw/compressed
    joy_topic: joy
    max_distance_error: 0.05
    publish_focus: true
    record_button: 2
    roi_height: 100
    roi_width: 100
    roi_x: 0.5
    roi_y: 0.5
    sphere_mass: 2.5
    sphere_radius: 0.65
    start_type_description_service: true
    v_max: 0.05
    visualize: true
    wrench_topic: /autofocus/wrench_cmds
    zeta: 1.0
gui:
  ros__parameters:
    data_path: /data/ViewpointGenerationData
    file_name: default
    show_axes: false
    show_curvatures: true
    show_fov_clusters: true
    show_grid: false
    show_mesh: true
    show_model_bounding_box: false
    show_noise_points: true
    show_path: false
    show_point_cloud: true
    show_region_view_manifolds: true
    show_regions: true
    show_skybox: true
    show_viewpoints: true
    start_type_description_service: true
orientation_controller:
  ros__parameters:
    Kd: 6.2
    Ki: 37.7
    Kp: 31.0
    adaptive_q_enabled: true
    adaptive_q_scale_moving: 50.0
    adaptive_q_tau_thresh: 0.5
    adaptive_q_w_thresh: 1.57
    anti_windup_enabled: true
    bounding_box_topic: /viewpoint_generation/bounding_box_marker
    camera_info_topic: /camera/d405_camera/depth/camera_info
    controller_type: PD
    crop_radius: 0.01
    crop_z_max: 0.4
    crop_z_min: 0.05
    d_max: 0.3
    d_min: 0.15
    data_path: /data/OrientationControlData
    depth_topic: /camera/d405_camera/depth/image_rect_raw/compressedDepth
    dmap_filter_max: 0.5
    dmap_filter_min: 0.07
    ema_enable: false
    ema_tau: 0.1
    enable_button: 0
    fluid_viscosity: 1.0
    ie_clamp: 5.0
    imu_accel_bias_rw_std: 0.0
    imu_accel_noise_std: 0.05
    imu_frame_id: eoat_camera_link
    imu_gyro_bias_rw_std: 0.0
    imu_gyro_noise_std: 0.005
    imu_rate_hz: 100.0
    imu_topic: /simulated/imu
    integral_alpha: 50.0
    jacobian_base_frame: ur_base_link
    jacobian_tip_frame: eoat_camera_link
    joy_topic: joy
    kalman_enabled: true
    kalman_model: KKF
    kalman_q_angle: 0.004
    kalman_q_dangle: 0.1245061
    kalman_q_ddangle: 1.0
    kalman_r: 0.1
    main_camera_frame: eoat_camera_link
    no_target_timeout_s: 0.25
    normal_estimation_method: RANSAC
    object: ''
    orientation_control_enabled: false
    pcd_downsampling_stride: 4
    robot_description_topic: /robot_description
    save_data: false
    simulate_imu: true
    sphere_mass: 2.5
    sphere_radius: 0.65
    standoff_m: 0.1
    standoff_mode: euclidean
    start_type_description_service: true
    surface_cloud_topic: /perception/surface_cloud
    surface_max_angle_deg: 30.0
    surface_min_points: 10
    surface_normal_frame: surface_normal
    surface_source: cloud
    target_frame: object_frame
    theta_max_deg: 90.0
    v_max: 0.1
    visualize_normal_estimation: false
    viz_enable: true
    zeta: 1.0
task_planning:
  ros__parameters:
    controller_manager_name: /controller_manager
    selected_region: 0
    selected_viewpoint: 0
    servo_controllers:
    - ur5e_forward_velocity_controller
    - turntable_forward_position_controller
    servo_node_name: servo_node
    settings.data_path: /data/ViewpointGenerationData
    start_type_description_service: true
    trajectory_controllers:
    - inspection_cell_controller
    viewpoints_file: ''
teleop:
  ros__parameters:
    deadzone: 0.05
    enable_button: -1
    force_scale: 0.6
    frame_id: eoat_camera_link
    invert_pitch: false
    invert_roll: false
    invert_x: true
    invert_y: true
    invert_yaw: true
    invert_z: false
    joy_topic: /joy
    pitch_axis: 4
    publish_rate: 10.0
    roll_axis_negative: 4
    roll_axis_positive: 5
    start_type_description_service: true
    torque_scale: 0.4
    twist_topic: /teleop/wrench_cmds
    x_axis: 0
    y_axis: 1
    yaw_axis: 3
    z_axis: -1
    z_axis_pull: 2
    z_axis_push: 5
viewpoint_generation:
  ros__parameters:
    model.mesh.file: /data/ViewpointGenerationData/teapot.stl
    model.mesh.units: in
    model.point_cloud.file: /data/ViewpointGenerationData/teapot_in/10000points.ply
    model.point_cloud.sampling.number_of_points: 100000
    model.point_cloud.units: m
    regions.fov_clustering.beta_weight: 1.0
    regions.fov_clustering.dof: 0.019999999552965164
    regions.fov_clustering.fov_diameter: 0.029999999329447746
    regions.fov_clustering.lambda_weight: 1.0
    regions.fov_clustering.max_point_out_percentage: 0.001
    regions.fov_clustering.maximum_iterations: 100
    regions.fov_clustering.normal_weight: 1.0
    regions.fov_clustering.number_of_runs: 10
    regions.fov_clustering.point_density: 10.0
    regions.fov_clustering.point_weight: 1.0
    regions.partfield.num_parts: 6
    regions.partfield.option: 0
    regions.partfield.use_agglo: true
    regions.partfield.with_knn: false
    regions.region_growth.batch_size: 1000
    regions.region_growth.curvature_threshold: 0.10000000149011612
    regions.region_growth.knn_neighbors: 30
    regions.region_growth.max_cluster_size: 100000
    regions.region_growth.min_cluster_size: 10
    regions.region_growth.normal_angle_threshold: 1.0471975803375244
    regions.region_growth.outlier_nb_neighbors: 20
    regions.region_growth.outlier_std_ratio: 2.0
    regions.region_growth.radius: 0.10000000149011612
    regions.region_growth.region_threshold: 0.20000000298023224
    regions.region_growth.remove_statistical_outliers: false
    regions.region_growth.seed_threshold: 0.10000000149011612
    regions.region_growth.spatial_hash_resolution: 0.05000000074505806
    regions.region_growth.use_spatial_hashing: true
    regions.segmentation_algorithm: partfield
    results.file: /data/ViewpointGenerationData/teapot_in/10000pointsin_results/6_regions_96_clusters_2026-06-23_22-40-03.json
    results.selected_cluster: 0
    results.selected_mesh: 0
    results.selected_region: 0
    settings.data_path: /data/ViewpointGenerationData
    settings.pv_opacity: 0.0
    start_type_description_service: true
    viewpoints.projection.focal_distance: 0.30000001192092896
    viewpoints.projection.hemisphere_points: 10000
viewpoint_traversal:
  ros__parameters:
    clear_paths: false
    compare: false
    compare_algorithms: -- none --
    multiplanning: false
    planner: ompl
    planning_group: disc_to_ur5e
    result.compare_algorithm: ''
    result.compare_distance: -1.0
    result.max_region_gap_pct: -1.0
    result.mst_lower_bound: -1.0
    result.optimality_gap_pct: -1.0
    result.primary_algorithm: ''
    result.primary_distance: -1.0
    start_type_description_service: true
    tsp_algorithm: greedy
    workspace.max_x: 1.0
    workspace.max_y: 1.0
    workspace.max_z: 1.0
    workspace.min_x: -1.0
    workspace.min_y: -1.0
    workspace.min_z: -1.0
